desihub/desisim

bin/pixsim-desi

Previous usage only worked when nspec<=500.  This change supports nspec>500, calculating which cameras are covered by those spectra.  It includes support for `nspec%500 != 0`, i.e. simulating some spectrographs completely and another one partially.

fix --nspec usage when nspec>500

---

py/desisim/io.py
py/desisim/obs.py
py/desisim/pixsim.py
py/desisim/test/test_io.py
py/desisim/test/test_pixsim.py

This addresses issue #19 by adding missing header keywords to the pix*.fits files: AIRMASS, EXPTIME, DATE-OBS, FLAVOR.  The keywords TELRA, TELDEC, and TILEID are propagated through the simspec file rather than the fibermap file, since the final real fibermap file may not have those.
Other items:
* get_tile_radec(tileid) now raises an exception if tileid isn't an integer
* quieter pixsim test of a case that was supposed to raise an error (details, if you care: exceptions that happen within a multiprocessing parallel processes can be obfuscated by the multiprocessing wrapper.  So _project was forcing a printout of any exceptions before passing it up the chain.  But when testing a case that is supposed to raise an exception, this was causing scary messages making it look like the tests had …

Header keywords

---

bin/quickgen

This PR corrects the number of fiberflats simulated for each spectrograph. Also hard coded nobj size is substituted by provided arguments. A numerical bug in cframe ivar is also fixed.

Corrects the number of fiberflats simulated

---

bin/simulate-templates
doc/tex/simulate-templates/simulate-templates.tex
py/desisim/io.py
py/desisim/templates.py

Dedicated templates for white dwarfs can now be generated.  For example, to generate 100 templates with g-band magnitudes in the range [16,19] and no radial velocity jitter do:
```
simulate-templates -o WD -n 100 --gmagrange-wd 16 19 --vrad-wd 0 0
```
Note that you first need to set the DESI_WD_TEMPLATES environment variable and to grab the corresponding "basis" templates from NERSC, e.g.,
```
export DESI_WD_TEMPLATES  ${DESI_ROOT}/spectro/templates/wd_templates/v1.0/wd_templates_v1.0.fits 
```
These templates are based on the theoretical DA white dwarf models built by Carlos Allende Prieto spanning a range of Teff [20,000-65,000 K] and log-g [7.0-9.5 cm/s] at high spectral resolution from 0.2-2.5 micron.
The I/O routines in desisim.templates were also moved to desisim.io.
Proper …

add support for generating white dwarf and QSO templates

---

bin/newexp-desi
bin/simulate-templates
etc/desisim.module
py/desisim/io.py
py/desisim/obs.py
py/desisim/targets.py
py/desisim/templates.py

I've tested the code, but independent eyes are welcome.  
The environment variables for all the individual target classes (DESI_ELG_TEMPLATES, DESI_LRG_TEMPLATES, etc.) are now obsolete.  All you need to set is
```
export DESI_BASIS_TEMPLATES=$DESI_ROOT/spectro/templates/basis_templates/v1.0
```
And then everything should "just work"
```
newexp-desi --nspec 500
```
FYI -- The following target classes are currently supported: ELG, LRG, QSO, STAR, STD (=FSTD), and WD.  In addition, BAD_QSO spectra are generated as interloper stars (although the stars don't yet satisfy the QSO color cuts.)

newexp-desi integrated with templates generated on-the-fly

---

py/desisim/io.py
py/desisim/test/test_io.py

Removed obsolete desisim.io.read_templates() function and added the same functionality to desisim.io.read_basis_templates()  Updated desisim.test.test_io.test_read_templates() class accordingly.
Note that the template I/O tests are quite fast (~<few seconds) for all object types except QSO, whose data model still needs to be updated to the latest incarnation of how the mock templates are being handled.  Nevertheless, running all the I/O tests is still relatively fast (<10 s).

fix template I/O unit test

---

py/desisim/obs.py
py/desisim/targets.py

This fixes #40 where new templates changed units but we didn't propagate those into the throughput calculations.  This topic could still use further cleanup (e.g. we still rely on magic knowledge that the sky spectrum in desimodel has units 1e-17 erg/s/cm2/A/arcsec2), but at least this PR gets us back to having photons on the CCD.  Nightly integration tests have been failing redshift fitting; this is likely why.
Tests are not yet automated with Travis, but they pass on my laptop.
Thanks to Govinda for noticing and reporting the problem.

fix units of object flux

---

py/desisim/__init__.py
py/desisim/obs.py
py/desisim/targets.py
py/desisim/test/test_obs.py

This PR fixes a problem reported by Ryan Staten: the FLUX and SKYFLUX in the simspec files were written in different units (1e-17 vs not), even though the headers claimed they were the same units.  This uses 1e-17 for both.  The PHOT and SKYPHOT extensions appear to be ok already.  Tests were added to check for unusually large or small flux and photon values.

fix FLUX vs. SKYFLUX units

---

bin/simulate-templates
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_templates.py

This PR fixes issues #48 and, critically, #47, among other minor bugs.
The incorrect emission-line strengths/fluxes (raised in #47) were due to a disastrous bug in which the emission-line width should have been *sigma* (km/s), when in fact it was being passed as *log10-sigma*.  I was also missing a factor of 1+z because apparently I didn't miss enough 1+z factors when I was in grad school.
While tracking this down, I decided to generate a new set of continuum (basis) templates for ELGs (now v1.5) which have better wavelength sampling around the positions of emission lines.  The wavelength sampling in the v1.4 templates was just sparse enough that a non-negligible amount of flux was being lost in the emission lines.  Because of this change, once this PR has been merged the …

fix emission-line strengths in templates and ensure reproducibility

---

bin/simulate-templates
py/desisim/__init__.py
py/desisim/obs.py
py/desisim/pixelsplines.py
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_templates.py

This PR fixes issue #52 and also adds (intrinsic) velocity broadening to the LRG templates based on some reasonable priors.  The smoothing is done using a module (pixelsplines) written by Bolton which caused some problems when broadening spectra with emission lines (i.e., the ELG spectra), so that was left off for now.  (The emission lines themselves, however, still have intrinsic velocity broadening.)

Fix issue/bug #52 and add fiducial velocity broadening to the LRG templates

---

bin/quickgen

This PR is to merge PR #56 into master and fixes #44.

Quickgen specsim

---

bin/quickbrick

Following a comment by @sbailey, I modified quickbrick to write the pre-downsampling high res source fluxes of simulated spectra along with the corresponding wavelength grid into the b-channel brick. @sbailey : Once merged into the master branch, could you tag a new version of desisim and have it installed on cori, so that I can re-generate the training sample for the challenge (using the same seeds as before so that the simulated spectra are the same as the current version).

Modification of quickbrick output in channel b brick

---

.travis.yml
py/desisim/io.py
py/desisim/obs.py
py/desisim/test/test_obs.py

A previous pull request on newexp-desi split --flavor 'science' into more specific categories like 'bright', 'dark', 'mws', 'bgs', 'elg', etc.  There were some leftover bugs in pixsim-desi expecting flavor='science'.  This PR fixes that.  Flavor is now propagated but for the most part not used other than distinguishing arc, flat, and other file formats for input spectra.

Bright pixsim

---

py/desisim/obs.py
py/desisim/targets.py
py/desisim/test/test_obs.py

If new_exposure flavor is 'bright', 'mws', or 'bgs', use the spec-sky-bright.dat file from desimodel instead of the default spec-sky.dat .  This will be superseded by a sky model that includes lunar phase, distance to moon, and elevation, but this change is better than simulating these targets with a dark night sky.
Includes tests that flavor='mws' indeed does produce a brighter sky than flavor='dark'.  Flavors 'bright' and 'bgs' are not yet implemented in other aspects of new_exposure and thus they aren't included in this test.

use bright sky for flavor=bright,bgs,mws

---

.travis.yml

This PR updates the numpy/scipy/astropy versions to match what is used in desispec.  I don't completely understand why this was necessary, but it fixes the travis tests.

bump numpy/scipy/astropy versions

---

bin/quickbrick
bin/quickgen

This is not ready to merge until I tag and release specsim v0.3, but now passes my tests on #80 using desihub/specsim#29.  Please review if you are interested.  I am finding identical results after the updates, but your mileage may vary.
Note that there are some trivial diffs in this PR where my editor (atom) automatically removed the invisible white space from the end of lines.  Sorry about that.  Could we standardize our whitespace conventions using [editorconfig](http://editorconfig.org)?   For example, the conventions I use in specsim are specified [here](https://github.com/desihub/specsim/blob/master/.editorconfig).

Update quickgen and quickbrick to new specsim API

---

py/desisim/targets.py

The default magnitude range for desisim.templates.STAR is not good for simulating standard stars, even when FSTD=True (that gets the colors right, but not the magnitudes).  This PR adds 16 < rmag < 19 constraints in desisim.targets.get_targets() when it generates stars to use as standard stars.
I think #64 will further clean this up by creating a separate FSTD class that could have appropriate magnitude ranges for FSTD.  This is an interim fix using the current multi-purpose STAR class.

fix mag range of simulated stdstars

---

.travis.yml
bin/pixsim-desi
py/desisim/pixsim.py
py/desisim/targets.py
py/desisim/test/test_targets.py

Starting a PR so that I can comment on this branch and its tests.
This PR updates the fibermap format to include the targeting mask bits and fills those in.
Tests will fail until the fibermap_format branch of desispec is merged into master.  That is in progress (i.e. don't merge this yet).

update fibermap format for target masks

---

py/desisim/targets.py
py/desisim/test/test_targets.py

Issue #71 to add newexp-desi --flavor "bright", "bgs", and "mws" was already implemented, albeit with a bug in "BRIGHT" vs. "bright".  This PR fixes that so that flavors are case-insensitive.

fix BRIGHT vs bright flavor bug

---

bin/newexp-desi
py/desisim/io.py
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_templates.py

Refactor STAR template class to make it easy to create multiple kinds of DESI stellar targets without proliferating arguments and if statements. There are now FSTD and MWS_STAR classes that inherit from the STAR class.  This is done "new class" style, I can change to the older style if preferred. Corresponding changes to target.py and io.py to use the new stellar template classes in newexp-desi for the mws, bgs and bright options.  The only remaining problem for bright sims is that spectre understands none of objtype=BGS, MWS_STAR or FSTD and uses the default for the throughput for all three.  That can only be right for the extended source or the stars, not both.

refactor stellar templates, issue #64

---

.gitignore
bin/quickbrick
bin/quickgen

The changes here depend on specsim changes in desihub/specsim#35, which will be merged and tagged (as v0.4) before this PR is merged.
Both quickgen and quickbrick now have much cleaner and consistent interactions with specsim.
Externally visible changes to quickgen:
* Add `--seed` option for reproducible results with different seeds (was always seed=0 before).
* Same noise realization is used for frame and cframe files.
* Noise and ivar are based on individual camera statistics, not the coadd, which is most noticeable at the camera edges.
* Resolution is convolved with the output pixel size.
* Sky model output now has non-zero ivar and noise (after fixing desihub/specsim/#1).
Externally visible changes to quickbrick:
* Random numbers are now reproducible.
* Remove `--wavestep` option (was …

Streamline use of specsim by quickgen and quickbrick

---

bin/newexp-desi
bin/pixsim-desi
py/desisim/obs.py
py/desisim/targets.py
py/desisim/test/test_io.py
py/desisim/test/test_targets.py

This fixes a critical bug in the random number seed propagation in get_targets_parallel() that was causing different spectra to receive the same TARGETID.  Tests have been added to verify that different seeds result in different TARGETIDs and different spectra, and to verify that the same seed results in the same TARGETIDs and identical spectra.
Assigning to @tskisner, though if @moustakas is in front of a computer right now I'd appreciate a review from him as well since he faced similar issues getting the random number seed propagation correct in the templates code.

fix random seed usage with parallelism

---

etc/travis_env_common.sh
py/desisim/obs.py

This PR for using an arc lamp emission line spectrum with wavelength in vacuum.
The template is at NERSC in /project/projectdirs/desi/spectro/templates/calib/v0.3
The hardcoded path in py/desisim/obs.py has been modified, we will need to remove this hardcoded path  in the future (the change is made in branch teststand).
This change from air to vacuum wavelength is needed to be consistent with the master version of desispec and specex, and the definitions of wavelength in the DESI target templates.

Wave in vacuum

---

.gitignore
MANIFEST.in
setup.py

This PR ensures that the py/desisim/data directory will always be treated as a legitimate part of the package, even though it contains no .py files.

Make sure data directory really is part of the package.

---

bin/desi_qa_zfind
py/desisim/spec_qa/redshifts.py

Set the matplotlib backend within `desi_qa_zfind` rather than `desisim/spec_qa/redshifts.py`.  Use 'agg' instead of 'Agg'.  These appear to be needed for getting `desi_qa_zfind` to work within a cronjob at NERSC (though it is different from the desispec QA code that sets that backend within the plotting code rather than the wrapper script, so we may need to revisit this...)

QA backend for cronjobs

---

etc/travis_env_common.sh

This PR updates the desisim-testdata version to 0.3.1, which itself updates the basis template set to v2.2 (see https://github.com/desihub/desisim-testdata/pull/4).  The new templates are located on NERSC in 
```
/global/project/projectdirs/desi/spectro/templates/basis_templates/v2.2
```
This PR also closes #113 and #118.

update template set to v2.2

---

bin/quickgen

This PR fixes a bug in quickgen where a mask was created as a float64 instead of an integer.  This previously silently (and perhaps incorrectly) "worked" until [desispec PR #212](https://github.com/desihub/desispec/pull/212) which enforced that masks should be integers not floats.  None of our tests caught this mismatch (see #96 for a request for quickgen tests).
Thanks to @profxj for reporting this bug.

fix quickgen mask dtype

---

py/desisim/qso_template/desi_qso_templ.py
py/desisim/templates.py

This PR fixes a minor issue related to the use of `resource_filename()`.  According to http://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access, one should not use `os.path.join()` to construct the second argument:
> Note that resource names must be /-separated paths and cannot be absolute (i.e. no leading /) or contain relative names like "..". Do not use os.path routines to manipulate resource paths, as they are not filesystem paths.
Also, I removed any remaining explicit use of `..`, even though they were not being used.

Resource filename use

---

bin/newexp-desi
py/desisim/batch/pixsim.py
py/desisim/scripts/pixsim.py
py/desisim/test/test_batch.py

This PR fixes a bug in the newexp-desi data flow where the batch jobs generating different exposures in parallel were all grabbing the same tileid and thus the same targets instead of having a different tileid per exposures.
We'll need to do a deeper refactor later coordinated with fiber assignment and the survey simulations, but this is the minimally useful step to actually get N different tiles instead of N different views of the same tile.
It is still borderline for whether or not pixel simulations can finish within the debug queue 30 minute time limit; I'll work on that in a separate branch + PR.

newexp different tileids in parallel

---

bin/desi_qa_zfind
doc/changes.rst
py/desisim/spec_qa/redshifts.py

Fixes fibermap OBJTYPE vs. simspec OBJTYPE usage so that fake QSO targets don't count in the QSO statistics.  This removes a vertical stripe at ztrue=0, but doesn't substantially change the interpretation of a large number of QSOs are failing redshift fitting.
Propagates desisim and specter versions to output figure instead of placeholder SIMSPECV=9.999.  Includes value of $SPECPROD and $PIXPROD, with a default of "unknown" if they aren't set. (separate to do: we should have pipeline include those in the file headers, and then get them from there instead relying upon whatever they are currently set to).
Misc plot ranges / axis tweaks.

QA zfind plot updates

---

py/desisim/obs.py
py/desisim/targets.py

We've updated desimodel/data/footprint/desi-tiles.fits to include the program for each tile, e.g. DARK, GRAY, BRIGHT.  `desisim.obs.get_next_field()` and `update_obslog()` had anticipated this, but using lowercase program names dark, gray, bright.  This PR fixes that.
Coming along for the ride is some work-in-progress for connecting truth table input to what is actually simulated, and removing some unused classes.
This PR is necessary to fix a broken integration test on master so I will self merge if there are no quick comments...

fix obs.get_next_tileid() for UPPERCASE program in desi-tiles.fits

---

doc/changes.rst
py/desisim/batch/pixsim.py

Adds propagation of random seeds to the `desisim.batch.pixsim` utility functions for batch generation of pixel-level simulations.  This is needed for before/after testing during the python3 migration (and is good to have anyway).
Note: the FITS header CHECKSUM and DATASUM headers include the timestamp of when they were generated, thus causing the sha1sum of the files to differ, even though the data and headers are otherwise identical.  To work around this, I compared the fits files from two batch newexp+pixsim runs using `fitsdiff` commands like:
```
fitsdiff -k CHECKSUM,DATASUM 20160818a/pix-r0-00000003.fits 20160818b/pix-r0-00000003.fits
fitsdiff: 1.1.1
a: 20160818a/pix-r0-00000003.fits
b: 20160818b/pix-r0-00000003.fits
Keyword(s) not to be compared:
CHECKSUM DATASUM
Maximum number of …
```

add rand seeds for batch pixsim

---

py/desisim/templates.py

This contains some minor updates to ```desisim.templates``` to close out #135.  In essence, to apply the color-cuts of one target class (e.g., ELGs) to another (e.g., stars):
```
from desitarget.cuts import isELG
from desisim.templates import STAR
ss = STAR(colorcuts_function=isELG) 
flux, wave, meta = ss.make_templates(5)
```
This would give you spectra of stars that pass the ELG target selection cuts, i.e., contaminant stars.
However, note that no stars *actually* pass these cuts, because the ELG target cuts were intentionally chosen to avoid the stellar locus.  We would need to apply the cuts to *noisy* photometry in order for this functionality to be useful.
@sbailey, ready for your review and merge and then I promise to stop making changes so we can finish the 2->3 transition.

Contaminants

---

bin/newexp-desi
py/desisim/io.py
py/desisim/scripts/quickgen.py
py/desisim/targets.py
py/desisim/test/test_templates.py

This PR fixes the MAG calculation for the simulated fibermap, which was broken as part of PR #132.  The previous flattening/slicing/stacking logic was wrong and the same magnitudes were replicated across multiple targets.  This was the core problem for the integration test failures.
Other changes that came long for the ride as a result of debugging this:
* adds exposure flavor "std" to newexp-desi to simulate a bunch of standards; useful for debugging
* several quickgen fixes:
* include fibermap in frame, cframe output
* include CAMERA header keyword
* fiberflats are referenced to 1.0 not 0.0

fix template fibermap mag; fix quickgen outputs

---

requirements.txt

desisim should now build successfully on ReadTheDocs.  You can view the successful build of this branch at https://desisim.readthedocs.io/en/rtd-test/.

Get desisim working on ReadTheDocs

---

py/desisim/scripts/pixsim.py

Without this line, I get an error running on python 2.7:
File "/home/kisner/software/desi27/lib/python2.7/site-packages/desisim-0.14.0.dev684-py2.7.egg/desisim/scripts/pixsim.py", line 232, in main
image, rawpix, truepix = desisim.pixsim.simulate(
AttributeError: 'module' object has no attribute 'pixsim'
This line fixes the error.  I am not sure why this does not get triggered by the desispec integration test!

Tiny one-line fix so that function from desisim.pixsim can be called.

---

py/desisim/scripts/quickgen.py
py/desisim/targets.py
py/desisim/test/test_quickgen.py

This PR
- adds airmass unit test for quickgen
- adds exposure time unit test for quickgen
- updates how exposure time is set with specsim v0.5
Note: bright time vs. dark time unit test is not included since quickgen does not yet include a moon phase option as quickbrick does.

added unit tests to quickgen and updated exposure time

---

py/desisim/scripts/quickbrick.py
py/desisim/test/test_quickbrick.py

This PR
* adds tests for quickbrick
* fixes #161 (updating how exposure time is set with specsim v0.5)
* fixes #162 (quickbrick crash)
* closes #96 (tests for quickgen and quickbrick)
It also fixes some bugs that weren't previously known and were caught by the new unit tests:
* --seed option wasn't working
* truth table output was corrupted using py3
However:
* The tests won't work on Travis until desihub/specsim#43 is addressed to reduce the specsim memory footprint or another workaround is found.  I've flagged these with `@unittest.skipIf('TRAVIS_JOB_ID' in os.environ)` wrappers.  Note that this also impacts the quickgen tests -- you can run them on a laptop with sufficient memory, but not on Travis.  In the meantime, we also won't get accurate coverage reports on coveralls.io for …

quickbrick tests and bug fixes

---

doc/changes.rst
py/desisim/test/integration_test_quickgen.py

This PR
- Provides an integration test for quickgen which verifies that quickgen output can be used as input for the full pipeline.
The integration test:
- Checks that all necessary environment variables are set.
- Generates 25 spectra flat, arc, and dark exposures via newexp-desi, then simulates this data using quickgen.
- Uses quickgen frame and fiberflat files as input for desi_compute_sky.
- Uses quickgen frame, fiberflat, and sky files, and star templates as input for desi_fit_stdstars.
- Uses quickgen frame, fiberflat, and sky files, and stdstars file generated by previous step as input for desi_compute_fluxcalibration.
- Uses quickgen frame, fiberflat, sky, and calib files as input for desi_process_exposure.
- Runs desi_make_bricks.
Note: desi_process_exposure fails due to 32 bit …

add integration test for quickgen

---

.travis.yml
py/desisim/scripts/quickgen.py
py/desisim/specsim.py
py/desisim/test/test_quickbrick.py
py/desisim/test/test_quickgen.py

This PR makes the quickbrick and quickgen tests ~2x faster by caching the `specsim.simulator.Simulator` object instead of recreating it anew every time.  It also enables these tests on Travis using specsim master and desisim master, now that specsim fits within the memory limits of Travis (as a side effect, the tests were also faster due to that change, even before this caching).  After the next tag of specsim, we can update this to use that tag instead.
Since the cached `Simulator` object may have been altered by the previous test, the caching code also caches the state for a few key variables and puts them back to their original state before returning the cached object:
* qsim.source.focal_xy
* qsim.atmosphere.airmass
* qsim.observation.exposure_time
* qsim.atmosphere.moon.moon_phase
* …

Cache specsim

---

doc/changes.rst
py/desisim/templates.py
py/desisim/test/test_quickbrick.py
setup.py

desihub/desitarget#113 split `desitarget.cuts.isQSO` into `isQSO_colors` and `isQSO_cuts`.  That broke desisim without us noticing.  This PR fixes that, while still supporting tag 0.7.0 and prior that have the `isQSO` function (while printing an error message about needing to upgrade).
It also fixes a problem where the lyman alpha test data wasn't installed by setup.py; I'm not sure how we passed tests previously without this.
I need this fix to get other tests to pass on an unrelated upcoming PR so I will self merge this in an hour if there are no objections.

fix tests to work with latest desitarget master

---

doc/changes.rst
py/desisim/quickcat.py
py/desisim/test/test_quickcat.py

This PR fixes fixes a major issue impacting redshift efficiency with quickcat.  Previously it was replacing any previously observed targets with new redshifts with ZWARN=0, and only assigning ZWARN flags to the current epoch of observation (which would then get blown away by the next epoch).  This includes tests that would have caught the problem in the first place.
I'll get this PR going with Travis tests while finishing the last round of quicksurvey tests using this.

fixes zeff

---

bin/quicksurvey
py/desisim/quickcat.py
py/desisim/quicksurvey.py

This PR fixes a crash-inducing quicksurvey bug that happened when the fiberassign output tiles do not match the observing conditions tiles from surveysim.  This can occur when the input target catalog is a subset of the overall footprint and fiberassign doesn't output a tile file for tiles that don't have any targets.  This update now gracefully handles that and proceeds with the tiles that are covered.
This PR also adds a `quicksurvey --start_epoch {n}` option to be able to restart where we left off from a previous run.  This should be useful for debugging and chaining together smaller jobs.
It also outputs more timestamps for debugging why quickcat isn't so quick.

fix tiles vs. obsconditions bug; add start_epoch option

---

doc/changes.rst
py/desisim/quicksurvey.py

This PR saves memory in quickcat by dropping some unused columns in the input catalogs; this might make it somewhat quicker.
It also fixes a bug when resuming quicksurvey at a given epoch after several epochs had previously been run (it reads in the previous MTL and zcat instead of treating them as None).

quicker quickcat maybe

---

py/desisim/lya_spectra.py
py/desisim/test/test_lya.py

This updates the API of `lya_spectra` (building off of #210) in order to accommodate the needs of https://github.com/desihub/desitarget/issues/136 when generating Lyman-alpha QSO spectra.
[The Travis tests were failing on my laptop because it couldn't load `speclite.filters` (which I don't understand), but let's see what happens here.]

update the API of lya_spectra to work with mock-->spectra connection

---

.travis.yml
py/desisim/io.py
py/desisim/lya_spectra.py
py/desisim/templates.py
py/desisim/test/test_templates.py

This PR addresses #200 (and a need of https://github.com/desihub/desitarget/issues/136) to support DB- and DA-type white dwarfs via a `subtype` optional input string to the `WD` class. As requested by @sbailey in #200, the subtype is also written to the output metadata table, which allows us to potentially expand this column to include other finer-grain properties of the various templates (see also the discussion in https://github.com/desihub/desitarget/issues/149).  I also added a couple basic unit tests.

support DA and DB white dwarf subtypes

---

.travis.yml
py/desisim/io.py
py/desisim/lya_spectra.py
py/desisim/pixsim.py
py/desisim/test/test_lya.py

A variety of test failures had crept into desisim mostly due to non-backwards compatible changes in other packages.  These went unnoticed in desisim since the Travis tests were pinned to older versions.  These changes get desisim back into compatibility with the latest versions of desispec, desitarget, and specter.
desisim itself will be ready for a fresh tag after confirming that these tests pass on Travis and merging.

Fix test failures

---

doc/changes.rst
py/desisim/templates.py

This PR contributes the 4-character fix to solve the `QSO.make_templates` scaling problem reported in #219.  The core problem was that it was looping over redshifts but then calling `desi_qso_templ.desi_qso_templates` with the full redshift array every time, thus it was generating N^2 QSOs while only picking N of them.

fix N^2 scaling of QSO.make_templates

---

.travis.yml
doc/changes.rst
py/desisim/obs.py
py/desisim/scripts/quickgen.py
py/desisim/specsim.py

specsim v0.8 broke quickgen because the Simulator outputs are now 2D arrays of multiple fibers instead of 1D arrays for a single fiber.  This PR provides the minimal fix to work around that, at the cost that quickgen now requires specsim v0.8 (i.e. it won't work with specsim v0.7 anymore).
A deeper refactor from @dkirkby will upgrade quickgen to do multi-fiber simulations taking into account their location on the focal plane; this PR is not that.
Another side effect of v0.8 was revealing a previously silent bug in `obs.new_exposure` where the EXPTIME header keyword was not being set for arcs and flats.  This PR fixes that.
Lastly, it also switches to using the `desisim.specsim.get_simulator()` wrapper to get a `Simulator` object; this lets the quickgen tests run much faster because they …

fix quickgen for specsim v0.8

---

bin/time-vdisp-cache
doc/changes.rst
etc/time-vdisp-cache
py/desisim/io.py
py/desisim/templates.py

This PR addresses #209 by using a smaller subset of unique, ungridded velocity dispersions (10% of the number of spectra being generated or 40, whichever is smaller) when generating galaxy (ELG, LRG, BGS) templates.  
I wasn't sure where to put it, but I added a small timing script to `desisim/bin/time-vdisp-cache` which compares the performance of the code with and without the incorporated changes (see below).  Building 100 templates is now a factor of ~12(!) faster with the new code vs the old code.  
The other change was to allow the [OIII]/H-beta line-ratio to meander outside of the prior range specified by the `oiiihbeta` optional input, which saved another ~20% of time.  This is a minor issue that's in the weeds for the current state of the code and can be revisited at a future …

significant speed-up of desisim.templates for galaxies

---

py/desisim/lya_spectra.py
py/desisim/qso_template/desi_qso_templ.py

I'm opening this PR to fix a "feature" in lya_spectra which resulted in simulated quasars with different redshifts than what's specified in the input files. This is a minimalist fix of [issue 227](https://github.com/desihub/desisim/issues/227). 
The only change is:
* set z_wind = 0 when constructing the qso object

set z_wind=0 in lya_spectra

---

py/desisim/templates.py

This logic should have been included in #229.  When `novdisp=True` I was incorrectly still caching the memory-hungry velocity dispersion convolution matrices.

do not cache blurmatrix when novdisp=True

---

py/desisim/templates.py

This PR intends to address issue #235 by removing the lyman-alpha absorption below the lyman-limit (which is already taken into account in the template).

remove lya absorption below lyman-lymit 

---

py/desisim/targets.py

In desimodel svn, `data/targets/targets.dat` recently got renamed to `targets.yaml` (it was already a yaml file) and a few entries changed names.  It also split `nobs_BG` into `nobs_bgs_bright` and `nobs_bgs_faint`.  This broke desisim master when working with desimodel data trunk.
This PR provides the minimal fix to work with desimodel trunk, while also printing a warning but proceeding anyway if a user still has `targets.dat`.  It does not try to handle BGS bright vs. faint in `desisim.targets.sample_objtype`; that should be part of a deeper refactor redoing how (if) `sample_objtype` is used.
Assigning @moustakas, but if he is too busy to check this out today I'll merge this afternoon anyway to get master/trunk versions of everything working together again before the nightly update at …

fix desimodel targets.dat vs. targets.yaml usage

---

doc/changes.rst
py/desisim/obs.py
py/desisim/scripts/quickgen.py
py/desisim/test/test_obs.py

This PR fixes some pieces of desisim that were broken by desihub/desispec#386 which became more picky about allowable exposure flavors when writing Frame objects.
The whole usage of "flavor" vs. "objtype" vs. "program" still needs to be cleaned up (see #97), but this at least gets us back to a working state on desisim + desispec master.

fix tests and code related to flavor=science

---

doc/changes.rst
doc/nb/simulating-desi-spectra.ipynb
py/desisim/scripts/quickgen.py

This PR adds a notebook tutorial for generating simulated spectra using `quickgen`.  However, the tutorial falls apart at the end when calling `desispec.scripts.makebricks` because `$DESI_SPECTRO_SIM`, `$DESI_SPECTRO_DATA`, and `$DESI_SPECTRO_REDUX` are not playing nice and I'm utterly confused about what to update without breaking things.  
Here's the direct link to the notebook -- @sbailey and @geordie666 please take a look if you get a chance.
https://github.com/desihub/desisim/blob/using-quickgen/doc/nb/simulating-desi-spectra.ipynb

simulating desi spectra notebook tutorial

---

doc/changes.rst
py/desisim/batch/__init__.py
py/desisim/batch/pixsim.py
py/desisim/obs.py
py/desisim/pixsim.py
py/desisim/qso_template/desi_qso_templ.py
py/desisim/quickcat.py
py/desisim/scripts/brightsims.py
py/desisim/scripts/pixsim.py
py/desisim/spec_qa/redshifts.py
py/desisim/specsim.py
py/desisim/targets.py
py/desisim/test/integration_test_quickgen.py
py/desisim/test/test_pixsim.py
py/desisim/test/test_quickgen.py

Small change to a bunch of files: use `desiutil.log` instead of the deprecated `desispec.log`, thus avoiding warning messages.

converts to using desiutil.log instead of desispec.log

---

.travis.yml
doc/changes.rst
py/desisim/templates.py

This PR fixes a bug identified by @akremin.  Previously this snippet of code would fail to return any templates fainter than `r=19.5`:
```
from desisim.templates import BGS
flux, wave, meta = BGS().make_templates(nmodel=100, rmagrange=(19, 20))
```
because the `BGS().colorcuts_function` was being set to *just* `desitarget.cuts.isBGS_bright`, which applies the magnitude cut `r<19.5` (note no equals sign).  
In this PR I allow the option of the `colorcuts_function` attribute to be a tuple and the code checks whether any (using logical or) of the "color cuts" are satisfied.  In the case of BGS these cuts are just magnitude cuts: `r<19.5` for the bright sample and `19.5<=r<20` for the faint sample.
This bug does not affect the 2% sprint simulations because there the target selection cuts were …

correctly select both "bright" and "faint" BGS templates by default

---

bin/wrap-fastframe
bin/wrap-newexp
doc/changes.rst
py/desisim/io.py
py/desisim/obs.py
py/desisim/scripts/fastframe.py
py/desisim/scripts/newexp_mock.py
py/desisim/simexp.py

This PR updates the wrap-fastframe and wrap-newexp MPI wrappers as well as fixing several bugs discovered while re-establishing the full end-to-end simulation + processing chain.
An API change is that desisim.simspec.simulate_spectra() now uses 1e-17 erg/s/cm2/A as default units instead of without 1e-17 (though you can still pass it a unit-ful astropy Quantity object and it will use that).
This has been tested with the minitest branch of https://github.com/desihub/two_percent_DESI .
Comments / suggestions are welcome, but I'd like to move forward with a fresh set of tags so comments sooner than later would be much appreciated.

newexp wrapper updates

---

bin/quickspectra
py/desisim/scripts/quickspectra.py

The PR to bring back the simple simulation tool we used to have (quickbrick) and that got lost.
The only way I found  to do a simple test of DESI performances was to write this new code.
This program (bin/quickspectra) directly writes a 'spectra' file that can be used as input to redrock.
The input file is either an ASCII file or a fits files (with HDUs WAVELENGTH and FLUX).
The code uses desisim.simexp.simulate_spectra as for the pipeline simulations, so there is no
duplication of simulation code.
Example 
```
quickspectra -i $DESIMODEL/data/spectra/spec-lrg-z0.7-zmag20.00.dat -o spectra-lrg.fits --repeat 10 --exptime 1500 --airmass 1.2
rrdesi spectra-lrg.fits --ncpu 8 --zbest zbest.fits
```

Quickspectra

---

py/desisim/scripts/quickgen.py

Update quickgen to define moon params, exptime, and airmass in correct order of precedence. Change default value of airmass to None! Default is maintained at 1.25 in code if passed airmass = None.

Quickgen now takes simspec moon params and fixed precedences

---

py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/specsim.py

Use the fast fiber acceptance of specsim in desisim (why two packages ...)
- In desisim/simexp.py , for source_type = ELG or LRG , use DISK or BULGE source profiles with 0.45" and 1" half light radii. For BGS, I implemented the same parameters as for LRG. We can change this if this is not the best choice. We may also include there a range of half light radii correlated with magnitudes if needed. 
- Added in bin/quickspectra a --source-type option to use the correct fiber aperture loss.
Code tested with quickspectra (S/N dropping by a factor 2.4 when ran with --source-type lrg or star )

Fast fiber acceptance

---

bin/pixsim_mpi
bin/pixsim_nights
bin/pixsim_nights_mpi
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/scripts/pixsim.py
py/desisim/scripts/pixsim_nights.py
py/desisim/test/test_pixsim.py

Submitting this PR on behalf of @tskisner after iterations with him and @julienguy about this branch and pixsim_fix (latest commit 54c4234) which addresses the same issue in a different way.
This fixes up the pixsim_nights_mpi wrapper around pixsim to work with multiple spectrographs and non-ideal packings of exposures into nodes.  It has been tested under various concurrencies and job sizes up to ~5 short nights of pixel-level simulations.  We'll proceed with this for larger runs for pipeline scaling tests.

fixing MPI wrappers for pixsim

---

py/desisim/obs.py
py/desisim/scripts/newexp_random.py

This PR fixes a bug where newexp-random was ignoring its --outdir option.

fix newexp-random --outdir option

---

py/desisim/quicksurvey.py

Small change to save RAM. Some columns are dropped in the tables used in `quicksurvey`.
Also forces garbage collection after deleting `mtl` tables.

drop columns from tables used in quicksurvey

---

.travis.yml
py/desisim/obs.py
py/desisim/scripts/newarc.py
py/desisim/scripts/newflat.py

- Use new arc lamp template from WINLIGHT data  (data from 2017/01/18, with a flux boost in B and Z to account for expected change of throughput)
- File saved in $DESI_ROOT/spectro/templates/calib/v0.4 (at NERSC)
- Changes to obs.py newarc.py  newflat.py which have a hardcoded calib version

Use new arc lamp template from WINLIGHT data

---

bin/wrap-fastframe
bin/wrap-newexp
doc/changes.rst

Small updates to `wrap-fastframe` and `wrap-newexp` while testing on the 2% redo data challenge.
`wrap-fastframe` now skips frames that have already been generated and only runs missing ones.  The check is meta-data intensive and kind of slow (~2 minutes for the 2% redo), but still faster than regenerating a bunch of frame files that already exist.  When the pipeline processing database exists, this could be updated to be more efficient.
`wrap-newexp` adding timing information to the success/fail messages.
I plan to self-merge these once Travis test pass.

wrap-fastframe and wrap-newexp updates

---

py/desisim/scripts/qa_zfind.py
py/desisim/spec_qa/redshifts.py

This is a minor fix to enable `desi_qa_zfind` to work even on specsim-based simulation productions that never needed specter.  The previous code would crash if specter wasn't in the known dependencies list of header keywords.  Now that is optional.

qa_zfind even if specter wasn't used

---

py/desisim/lya_spectra.py

Tiny pull request to change the default value of lyaforest in desisim.lya_forest. @moustakas, I guess it should be trivial to merge, right? It fixes issue #291

do not add random lya forest when also reading lya forest from file

---

bin/wrap-fastframe
py/desisim/scripts/fastframe.py

Enable fastframe and wrap_fastframe to directly write cframe files.
This is convenient to study the variation of redshift efficiency with or without the pipeline fiberflat, sky subtraction and flux calibration.

add option to directly write cframes

---

doc/conf.py
py/desisim/simexp.py
py/desisim/test/test_obs.py

This PR fixes #298, which turned out to be a test bug that was exposed by a different bug fix in my hotfix to desisim master this morning which was needed due to desispec dropping the Brick class (deprecated in favor of Spectra instead).

fix bright/dark test

---

py/desisim/scripts/pixsim.py

- Default option value nspec=500 was breaking simulations of more than one spectrograph. This bug was introduced recently.
- It's a two line change to the code but I submit a PR anyway in case this fix is posing other difficulties.

fix bug in pixsim when simulating more than one spectro 

---

doc/changes.rst
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/test/test_quickspectra.py

This PR
* fixes quickspectra, which was broken by [desispec PR #473](https://github.com/desihub/desispec/pull/473) removing `desispec.spectra.spectra_dtype`.  Thanks to @paulmartini for reporting.
* Adds quickspectra tests that would have caught that bug.
* Fixes quickspectra --seed option, which appears to have never worked due to randomness in specsim quick fiberloss calculations (see [specsim #83](https://github.com/desihub/specsim/issues/83)).  This is also included in the unit tests now.
Unfortunately quickspectra is broken in the desisim 0.23.0 tag used by the desimodules 17.12 release, but this PR restores it to working in master for the next tag and includes basic tests to keep it working.

fixes quickspectra

---

.travis.yml
doc/changes.rst
py/desisim/lya_spectra.py
py/desisim/templates.py

This PR is tangentially related to #297.  It adds the option of not resampling the QSO templates in wavelength, which may be necessary when applying the Lya forest transmission *outside* (i.e., after) making the templates (also softly related to https://github.com/desihub/desitarget/issues/252).
This PR also adds the documentation requested by @sbailey in #303.  See also cells [32-38] of the [simqso-templates notebook](https://github.com/desihub/desisim/blob/master/doc/nb/simqso-templates.ipynb) for a demonstration of how the `qsometa` object can be used to regenerate simqso templates.

optionally do not wavelength resample the QSO templates 

---

.travis.yml
doc/changes.rst
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/scripts/pixsim.py

Changed MPI bcast to Bcast to take advantage of faster numpy arrays vs slower python objects. Instead of preallocating as 'None', this required a little more work to correctly pre-allocate the empty numpy broadcast arrays. 
Speed testing is still in progress, but on a single node for a single processor (Haswell), the runtime for the MPI version is approximately 7 percent slower than the multiprocessing version. As the number of processes grow, MPI becomes increasingly slower than multiprocessing due to overhead. This may need to be improved in the future with functions like MPI scatter and gather, rather than broadcast.

changes to speed up MPI by reducing amount of broadcast data

---

doc/changes.rst
py/desisim/io.py
py/desisim/obs.py
py/desisim/simexp.py
py/desisim/specsim.py

This PR does the minimal change to fix #318, where @julienguy noticed that the pixsims were getting double convolved by the PSF.  The fix is to use `specsim.simulator.Simulator(camera_output=False)` and write the unconvolved electrons to the simspec output files.
fastframe uses the FLUX (not PHOT) HDUs so isn't impacted.  This fix is fragile since it risks us making the opposite mistake later and thinking that the simspec PHOT HDUs are convolved when now they aren't.  A better long term solution would be to store just the FLUX in the simspec files, and re-run specsim on-the-fly for pixsim as is done for fastframe.  However, @lastephey is in the middle of refactoring the MPI pixsims to improve it's performance and I want to let that settle before making another change on top of it. …

fix double PSF convolution in pixsim

---

.travis.yml
py/desisim/quickcat.py
py/desisim/quicksurvey.py
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/spec_qa/utils.py
py/desisim/test/test_quickcat.py

This PR updates the imports of `desitarget.targetmask.desi_mask`, `bgs_mask`, etc. after the restructuring from desihub/desitarget#282.  It also fixes #314 by updating the travis tests to depend upon tags instead of master.

update desitarget.targetmask.desi_mask imports

---

doc/changes.rst
py/desisim/obs.py
py/desisim/scripts/fastframe.py
py/desisim/scripts/newexp_mock.py
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py

Previous PR #320 fixed the PSF double convolution for newexp_random but not newexp_mock (Mea culpa!).  This PR fixes it for newexp_mock too.  I plan to do a few more tests before being ready to merge but I'm opening this PR now to get the travis tests running.

fix psf convolution for newexp_mock

---

py/desisim/io.py

This pull request should address the problem in desisim issue #330 (https://github.com/desihub/desisim/issues/330)
In the MPI version, because we don't have access to the simspec fits file on all ranks, we sort instead by flavor ('arc', 'flat', or 'science').

fixed broken arc for mpi, sorting by flavor

---

py/desisim/simexp.py

Correcting a tiny bug that consisted of an equality check (==) instead of a less-than-or-equal (<=)

Make redshift check and correction consistent

---

.travis.yml
doc/api.rst
doc/conf.py
py/desisim/io.py
py/desisim/obs.py
py/desisim/scripts/pixsim_nights.py
py/desisim/simexp.py

This PR fixes #309.  I am still working out the bug related to `Table()` units.  However, I have determined the exact cause of this bug, and it is **NOT** due to `Table()` somehow requiring that all columns have units.  Please see astropy/astropy#7279 for the exact cause, but in brief, some tables produced by desisim have columns with `dex` as the unit.  There is no problem with a `Table()` having a column with this unit.  The problem is converting that unit *into a FITS-compliant unit*.
I will consider some simple workarounds, like not using 'dex' as a unit.

Astropy 2 compatibility

---

py/desisim/scripts/pixsim.py
py/desisim/test/test_pixsim.py

desihub/desispec#523 moved the output location of preprocessed pix files, which broke pixsim tests because they didn't pre-create the necessary output directory.  This PR fixes that.
A better long-term solution might be to add a `mkdir` option to `desispec.io.findfile` similar to what is already in `desisim.io.findfile`.  Maybe.  For now this PR just makes the minimal change in desisim to restore its tests when running against desispec master.

fix pixsim for new pix file output location

---

.gitignore
.travis.yml
doc/changes.rst
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/scripts/pixsim.py
py/desisim/scripts/pixsim_nights.py
py/desisim/test/test_io.py
py/desisim/test/test_pixsim.py

Fixes pixsim to match desihub/desispec#545 which renamed preprocessed spectrograph data from pix*.fits to preproc*.fits and moved it from the raw data directory to a spectro pipeline step under $DESI_SPECTRO_REDUX/$SPECPROD.

pix file renamed preproc

---

doc/changes.rst
py/desisim/obs.py
py/desisim/scripts/newarc.py
py/desisim/scripts/newexp_mock.py
py/desisim/scripts/newflat.py
py/desisim/simexp.py

This PR fixes desihub/desispec#521 by ensuring that fibemap files have EXTNAME=FIBERMAP set.  It also fixes a bug in the `newexp-mock --nspec` option that I found while testing this.  I tested fibermap outputs from `newflat`, `newarc`, `newexp-mock`, and `newexp-random`.
I plan to self-merge after (if?) Travis tests pass to move on with software release 18.3 integration testing.

fix EXTNAME=FIBERMAP and newexp-mock nspec option

---

doc/changes.rst
py/desisim/scripts/qa_zfind.py
py/desisim/spec_qa/redshifts.py
py/desisim/spec_qa/utils.py

Calculate the summary QA statistics for redshift performance
provided an input truth and measured redshift tables.  Tested
to work with truth.fits and zcatalog-mini.fits from reference run 18.3
Here is the code snippet
```
from desisim.spec_qa import redshifts as dsqa_z
from astropy.table import Table   # The underlying code uses MaskedColumn and other astropy functionality
zcat = Table.read('spectro/redux/mini/zcatalog-mini.fits')
truth = Table.read('targets/truth.fits')
dsqa_z.match_truth_z(truth, zcat, mini_read=True)
metric_dict = dsqa_z.summ_stats(truth)
```
Addresses Issue #346 
Have also tested that --yaml_file= option in desi_qa_zfind works
with reference run 18.3.  Will add it to the minitest Notebook soon.

Redshift QA metrics from summary tables

---

doc/changes.rst
py/desisim/io.py
py/desisim/obs.py
py/desisim/pixsim.py
py/desisim/scripts/fastframe.py
py/desisim/scripts/pixsim.py
py/desisim/scripts/qa_s2n.py
py/desisim/scripts/qa_zfind.py
py/desisim/scripts/quickgen.py
py/desisim/spec_qa/redshifts.py
py/desisim/spec_qa/utils.py
py/desisim/test/test_io.py
py/desisim/test/test_obs.py
py/desisim/test/test_quickgen.py

Integrates the ztests method from desitest mini-Notebook within
the existing redshift QA.  Tested against the summary tables from
18.3 with code like this:
```
from desisim.spec_qa import redshifts as dsqa_z
truth = Table.read('truth.fits')
zcat = Table.read('zcatalog-mini.fits')
dsqa_z.match_truth_z(truth, zcat, mini_read=True)
good, fail, miss, lost = dsqa_z.zstats(truth, objtype='STAR')
```
Also refactored scripts to use qaprod_dir 
and cleaned up several of the summary 
redshift stats.

Add ztests method to redshift QA

---

py/desisim/pixsim.py
py/desisim/scripts/pixsim_nights.py
py/desisim/test/test_pixsim.py

This pull request makes use of the newly implemented simulate_exposure function which handles all the MPI I/O for pixsim. Pixsim_nights enables the user to specify the nights they would like to simulate and optionally specific cameras and cosmics for each exposure. Several utility functions allow the exposures and frames to be divided among the nodes in a sensible way. The job will fail with a helpful error message if the nodes cannot be filled appropriately.

working pixsim_nights

---

doc/changes.rst
doc/nb/Confusion_matrix_spectypes.ipynb
py/desisim/spec_qa/redshifts.py

Compares truth vs type recovered from RedRock.
Generates a dict holding the matrix.
See https://github.com/desihub/desisim/blob/confuse_me/doc/nb/Confusion_matrix_spectypes.ipynb
for usage.
Have tested on 18.3 mini-test with:
```
from astropy.table import Table
from desisim.spec_qa import redshifts as dsqa_z
simz_tab = Table.read('truth.fits')
zcat = Table.read('zcatalog-mini.fits')
results = dsqa_z.spectype_confusion(simz_tab, zb_tab=zcat)
```
Addresses Issue #348

Generate Confusion matrix related to spectral types

---

bin/wrap-newexp
py/desisim/scripts/newexp_mock.py
py/desisim/templates.py

This PR fixes a bug in wrap-newexp when working on a list of exposures that doesn't start with expid=0 (!).
While I was at it, I also fixed a deprecation warning arising from `npix` being calculated as a float but used as an integer.

newexp-mock require expid not obsnum

---

py/desisim/lya_spectra.py
py/desisim/scripts/quickquasars.py

Add transmission from metals given the transmission from Lya.
`--metals SiII(1260) SiIII(1207) SiII(1193) SiII(1190) `?
To get the parameter for SiII(1260) SiIII(1207) SiII(1193) SiII(1190) I compared to the data.
Do we want to get the parameter for all the other lines CIV..., do we want to make a deeper study of the values of the parameters?
Such a study could take more time.
Here is a comparison of the 1d-correlation for: data, "noiseless+Transmission+Lya" and "noiseless+Transmission+Lya+Metals"
The unique small issue is that if setting something like SiII(1260) (wavelength>1215.67), because of the wavelength difference between Lya and this line, a part of the transmission at small wavelength is exactly 1.
@ngbusca did you notice that when doing the mockExpander? What solution did you …

add transmission of metals from LYA transmission

---

doc/changes.rst
py/desisim/templates.py

Simple PR to address request #324.  @londumas I haven't tested this extensively, so please make sure Lyman-alpha and other lines are where they should be!
Note that for issues of speed (i.e., not having to resample) and because of the way `desisim.templates` uniquely interfaces with `simqso` (i.e., uniquely, compared to the other templates which we build in-house) you have to specify the `restframe` option in the class constructor itself, e.g.,
```
from desisim.templates import SIMQSO
qso = SIMQSO(restframe=True)
flux, wave, meta = qso.make_templates(5, seed=1)
```
Finally note that the output (rest-frame) wavelength vector is hard-coded to 900-60000 A at a resolution of 8000, but this can be changed easily.

add restframe option to SIMQSO

---

py/desisim/archetypes.py

This PR fix issue https://github.com/desihub/desisim/issues/357 by computing the chi2 between normalized archetypes. Thanks to that the chi2 matrix is symmetric. The amplitude matrix is however given for the input spectra, not for the normalized one. If no error vector is given, this PR is way faster than the previous code.

correct computation of chi2 and amplitude between archetypes

---

py/desisim/io.py
py/desisim/scripts/pixsim.py
py/desisim/test/test_io.py
py/desisim/test/test_pixsim.py

This is a companion PR to desihub/desispec#648, to write simulated raw data into per-exposure directories `$DESI_SPECTRO_SIM/$PIXPROD/{YEARMMDD}/{EXPID}/` instead of `$DESI_SPECTRO_SIM/$PIXPROD/{YEARMMDD}/{EXPID}/`.
To be merged after desihub/desispec#648

raw data now under NIGHT/EXPID/ not just NIGHT/

---

bin/wrap-fastframe
doc/changes.rst
py/desisim/io.py
py/desisim/scripts/newexp_mock.py
py/desisim/test/test_io.py

This PR fixes a few leftovers from the switch to raw data in `basedir/NIGHT/EXPID/` directories instead of all exposures in a single `basedir/NIGHT/` directory.  In particular:
* `wrap-fastframe` looks for input files with the correct glob (one level deeper)
* `wrap-fastframe` parses the night from the path correctly
* `newexp-mock` passes `expid` to `desisim.io.simdir` to get correct output location
* `desisim.io.simdir` no longer has a default `expid=0` which was previously leading to science exposures silently being written to the incorrect directory.
@weaverba137 these changes are required for the minitest notebook to work.  I have tested them by taking the minitest notebook up to these stages and failing, and then debugging the `newexp-mock` and `wrap-fastframe` commands separately …

fix newexp-mock and wrap-fastframe NIGHT/EXPID/ vs. NIGHT/ parsing

---

doc/changes.rst
py/desisim/templates.py

This PR fixes desihub/desitarget#323 where `select_mock_targets` became mysteriously slower for BGS and ELG using the latest desiconda.  I traced this to a single line in `desisim.templates.EMSpectrum`:
```python
emspec += amp * np.exp(-0.5 * (self.log10wave-thislinewave)**2 / log10sigma**2) \
/ (np.sqrt(2.0 * np.pi) * log10sigma)
```
The Gaussian is evaluated at all wavelengths `self.log10wave` instead of just a few sigma around `thislinewave`.  For earlier desiconda installations using the Intel Math Kernel Library (MKL) 2018.0.1, this wasn't a problem.  But newer desiconda installations use MKL 2018.0.2, which is 10x slower for this particular case of evaluating exponentials of large arrays of large negative numbers that will mostly result in 0.
I fixed this by pre-filtering the …

faster emission line sims for MKL>=2018.0.2

---

.travis.yml
py/desisim/dla.py
py/desisim/scripts/quickquasars.py
py/desisim/scripts/quickspectra.py
py/desisim/test/test_quickgen.py
py/desisim/test/test_quickspectra.py

numpy.random.poisson has the drawback of using a varying number of random numbers depending on the mean value (the argument of the function). this is problematic for some applications like testing the effect of DLA on the Lya correlation function where one would like to preserve the random numbers used to simulate the instrumental noise when adding DLAs or not. This PR fixes this by allowing the use of numpy.random.normal instead of numpy.random.poisson in specsim.simulator.Simulator.generate_random_noise.
Solves issue #386.
(Need to rerun tests when the equivalent PR in specsim is merged.)

No poisson

---

.travis.yml
doc/changes.rst
py/desisim/io.py
py/desisim/obs.py
py/desisim/scripts/quickgen.py
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_obs.py
py/desisim/test/test_quickcat.py
py/desisim/test/test_templates.py

Update templates code to accommodate the changes to `desitarget` in https://github.com/desihub/desitarget/pull/338, largely related to changing the standard-star designation from `FSTD` to `STD`.

update templates to DR7 standard stars

---

.travis.yml
bin/quicksurvey
doc/changes.rst
py/desisim/io.py
py/desisim/obs.py
py/desisim/quickcat.py
py/desisim/quicksurvey.py
py/desisim/scripts/quickgen.py
py/desisim/scripts/quickquasars.py
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_obs.py
py/desisim/test/test_quickcat.py
py/desisim/test/test_templates.py

This resurrects quicksurvey to enable simulations of survey with multiple epochs.  It also removes references to the template (features file).  The primary change is in the subprocess call, which now uses the fiberassign script rather than going directly to the c++ executable fiberassign_exec.

Update to use fiberassign script in place of fiberassign_exec from c++ code

---

.travis.yml
doc/changes.rst
py/desisim/scripts/quickspectra.py
py/desisim/simexp.py
py/desisim/targets.py
py/desisim/test/test_quickcat.py

Updates for compatibility with desitarget/0.23.0 which renamed bit STD -> STD_FAINT.
When it wouldn't clutter the code too much, this also maintains backwards compatibility with previous names (STD, STD_FSTAR).  quickspectra and quickcat are not backwards compatible but simexp is.
Companion PR to desihub/desitarget#341 .

update to STD_FAINT

---

bin/wrap-newexp
doc/changes.rst
py/desisim/obs.py
py/desisim/scripts/newexp_mock.py
py/desisim/simexp.py

* Adds an `nside` optional argument to `wrap-newexp` and `newexp-mock` (addressing #379).
* Adds an `overwrite` argument to `obs.new_exposure` (defaulting to `False`) to optionally overwrite existing files (useful for testing).

add nside and overwrite options to wrap-newexp and obs.new_exposure, resp.

---

doc/changes.rst
py/desisim/data/forbidden_lines.ecsv
py/desisim/templates.py

Addresses #417 by adjusting the emission-line spectra in the ELG and BGS templates to account for (in)consistencies relative to SDSS/BOSS stacks.
Specifically, I've added the [OI] 6300,6363, [SIII] 9069,9532, [ArIII] 7135,7751, and MgII 2803/2796 emission-line doublets.  The relative strengths of the forbidden doublets relative to one another is set by nebular physics, while the MgII doublet strength I've set to be unity.  
In addition, for simplicity I took the strength of the stronger line (in each doublet) relative to H-beta to be a (physically motivated) constant, which definitely leaves room for improvement.
I also added a minor speed-up in that only lines within the specified (output) spectral range are handled.
I'll merge once tests pass (although the template tests already pass on …

adjust and update nebular emission lines in galaxy templates

---

py/desisim/scripts/quickquasars.py

This PR supersede #449 due to some confusing conflicts when merging with master branch. 
Summary of this PR:
Adds a random shift to the true redshift. This is to simulate as if we have run redrock to find the redshift from the spectra. This shift is now sampled from a modified Cauchy distribution instead of a Normal (as it was before), this is motivated by the distribution observed in Zarrouk et al 2018 (https://arxiv.org/pdf/1801.03062.pdf) See #441. L609
Right now we completely changed from normal to lorentzian distribution. If you think we should keep the option of a gaussian, we can add it as an option with two parameters.
Adds a shift to redshift according to table 4 of du Mas des Bourboux et al 2017 (https://arxiv.org/pdf/1708.02225.pdf) L571
Change the location for the addition of …

Add feature to quickquasars

---

py/desisim/scripts/quickquasars.py

Fix issue https://github.com/desihub/desisim/issues/456:
- Correct the TARGETID of truth for all 4 HDUs
- Change `z` to `Z` for DLA

Fix quickquasars targetid truth

---

doc/changes.rst
py/desisim/scripts/qa_s2n.py
py/desisim/spec_qa/s2n.py

Refactor `desi_qa_s2n` to perform all S/N calculations on all cframes (per channel)
before then parsing by objtype, etc.
Also updated for new Truth table.
Tested on mini 18.7.  Now runs in ~120s.
Addresses Issue #444

Refactor S/N QA

---

bin/precompute-template-colors
doc/changes.rst
py/desisim/io.py
py/desisim/templates.py

Simple PR which adds a command-line script to compute colors for ELG, BGS, and LRG templates on a uniform redshift grid from `z=0-2.5` and fixed (rest-frame) colors for STAR and WD templates.  The results are written to a dedicated HDU named `DESI-COLORS` which is only read by `io.read_basis_templates` if present (in other words, the changes here are backwards-compatible).
Note that for STAR templates we do not compute WISE colors because the templates do not extend red enough, but this issues is handled elsewhere (e.g., in `templates.STAR.make_templates` and `desitarget.mock.mockmaker.STARMaker`).
For the record, the following filters are used: `decam2014-*`, `BASS-*`, `MzLS-z`, and `sdss2010-*`.
The new set of templates (with this HDU included) will be added in a separate PR after some …

precompute colors for star and galaxy templates

---

.travis.yml
doc/changes.rst

Update travis testing to use desisim-testdata/0.6.1.  This version of the test data matches basis_templates v3.1; the etc/desisim.module file was updated directly in master to use that basis_templates version.
No code changes.

use desisim-testdata 0.6.1

---

doc/changes.rst
py/desisim/spec_qa/s2n.py

PR #459 made S/N QA much faster, but was tested on reference run 18.7 which used an older format of truth tables, and that PR commented out the code that let it work with the newer format.  This PR re-enables the QA to work on the newer truth tables that keep per templatetype specific columns (like OIIFLUX or LOGG) in separate HDUs.  It does this in a way that is also backwards compatible with the older format.
Tested on reference run 18.7 (old format) and a current run of master (new format).
Needed for the 18.12 integration test.

re-enable newer per-templatetype truth tables for QA

---

py/desisim/lya_mock_p1d.py
py/desisim/qso_template/desi_qso_templ.py
py/desisim/spec_qa/redshifts.py
py/desisim/templates.py

Move to a common definition of speed of light. Step toward fixing issue https://github.com/desihub/desisim/issues/477.

import speed of light from scipy

---

py/desisim/simexp.py

The change suggested by @sbailey solves the issues with newexp-mock found in the minitest.

fixing bug with objmeta

---

.travis.yml
bin/wrap-fastframe
bin/wrap-newexp
py/desisim/scripts/newexp_mock.py
py/desisim/simexp.py

Updates to support the simulation chain with SV1_DESI_TARGET in prep for Survey Validation.
@michaelJwilson please try this "sv" branch with fastframe and report any problems to this PR and we'll get them fixed as part of this update.

support SV, especially SV1_DESI_TARGET

---

py/desisim/lya_spectra.py
py/desisim/scripts/quickquasars.py

This PR allows to run quickquasars on the newest version of London mocks (>v7.3), which includes metal transmission in separate HDU's which is to be used for individual tunning of the metals. It is compatible with old format and with the final format once the metals are tunned individually. Optional argument names didn't change, only allows for a list of arguments instead of being a boolean argument. Works as follows:
--metals-from-file  all (default)   : Looks for "F_METALS" or "METALS" HDU in transmission file, to be used for old format or final format. 
--metals-from-file all-dev : Adds all the current metals added in the transmission files['F_SI1260','F_SI1207','F_SI1193','F_SI1190']    
--metals-from-file  SI1260 SI1207 : Adds only the specified metals if present in transmission …

Qquasar readmetal

---

py/desisim/lya_spectra.py
py/desisim/scripts/quickquasars.py

This PR fixes a bug found when trying to run quickquasar on the London mocks v8.0, and we are also using it to save global seed and pixel seed in the truth files. Output is as indicated below... 
```
test=fits.open("/project/projectdirs/desi/users/alxogm/desi/mocks/london/metals/v8.0.0/truth-16-0.fits")
test.info()
Filename: /project/projectdirs/desi/users/alxogm/desi/mocks/london/metals/v8.0.0/truth-16-0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
0  PRIMARY       1 PrimaryHDU       6   ()      
1  TRUTH         1 BinTableHDU     51   5R x 18C   [K, 10A, 10A, I, K, E, E, 15A, E, E, E, E, E, E, D, D, D, E]   
2  QSO_META      1 BinTableHDU     21   5R x 5C   [K, E, 5E, 186E, I]   
test[0].header
[32]:
SIMPLE  =                    T / conforms to FITS standard …
```

Fix bug when reading transmision files with hdu named F_METALS.

---

.travis.yml
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/scripts/pixsim.py
py/desisim/test/test_io.py
py/desisim/test/test_pixsim.py
py/desisim/test/test_quickgen.py

This PR makes updates to the pixsim header keywords for consistency with real data, in preparation for Survey Validation.
* Switches from CCD amp names 1-4 to amp names A-D (like real data)
* Requires deishub/desispec#807 to be able to preproc these
* Drops GAIN* keywords that ICS isn't planning to write into real data
* $DESI_SPECTRO_CALIB tracks our gains instead in a more flexible way
* Adds additional keywords to match real data.  Some are useful (e.g. "ST" = local sidereal time); others are amusingly mysterious (e.g. "VESSEL").
* MJD -> MJD-OBS
Also, if pixsims MPI subcommunicators don't pack evenly into the nodes, it now prints a warning instead of raising an error.  This makes it easier to simulate a prime number of exposures without being super constrained on how many nodes you …

pixsim updates for SV and consistency with real data

---

py/desisim/quickcat.py
py/desisim/test/test_quickcat.py

(Open for discussion, not ready to merge yet)
This fixes the bug with wrong `NUMOBS` counts after repeated observations.
The issue was that for these lines to work
```python
#- targets that are in both zcat and newzcat
repeats = np.in1d(zcat['TARGETID'], newzcat['TARGETID'])
#- update numobs in both zcat and newzcat
ii = np.in1d(newzcat['TARGETID'], zcat['TARGETID'][repeats])
orig_numobs = zcat['NUMOBS'][repeats].copy()
new_numobs = newzcat['NUMOBS'][ii].copy()
zcat['NUMOBS'][repeats] += new_numobs
newzcat['NUMOBS'][ii] += orig_numobs
```
the `TARGETID` in `zcat` and `newzcat` should have the same ordering. 
The modification in `quickcat` fixes that bug. But it gives problems in the tests where the `TARGETID`s are expected somehow to have a different `TARGETID` ordering.
Do we have any …

Fixes bug in quickcat

---

.travis.yml
py/desisim/scripts/quickquasars.py

After creating tag 0.33.0, tests were running with Numpy/1.17 and failing.  This sets the version to 1.16.
@sbailey, there are some other versions in the .travis.yml file that could use some freshening up.  Do you want to go ahead with that?

Pin numpy version

---

bin/wrap-newexp
py/desisim/scripts/newexp_mock.py
py/desisim/simexp.py

This PR updates desisim newexp-mock to support the updates in desihub/desitarget#543 to split the mocks into separate dark/bright directories, just like the target and MTL files for real data are split.
In particular it uses the PROGRAM of a tile to propagate `obscon` to `get_mock_spectra` which passes it to `desitarget.mock.io.findfile`.  The mapping of PROGRAM to obscon is a bit fragile.
This has been tested with the minitest notebook (along with desihub/desitarget#543 and desihub/fiberassign#223).

support mocks in dark/bright subdirs

---

doc/changes.rst
etc/desisim.module

In this PR I update `desisim.module` to use the `v3.2` basis templates, which are identical to `v3.1` except for the BAL templates, which were updated from `v2.1` to `v3.0` (see #504 and #509)--
https://desi.lbl.gov/svn/data/basis_templates/tags/v3.2/
@jfarr03 @paulmartini let's hold off on merging this PR until the `19.9` software release is out.
At that point, @sbailey, you'll also need do some magical incantation at NERSC to use these updated basis templates and we'll also need to update the instructions on the wiki:
* https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata
* https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#Defineinputtemplatelocations
@paulmartini @jfarr03 any tests of `quickquasars` using these templates (which you can do by …

update to v3.2 basis templates

---

py/desisim/scripts/newexp_mock.py

Small change to newexp_mock.py to look for new fiberassign file names (fiberassign-EXPID.fits), while falling back to looking for old fiberassign file names (tile-EXPID.fits), while deprecating the really old fiberassign file names (tile_EXPID.fits).  Maybe we're done renaming those files now that we're using them on sky...
I plan to self-merge this once tests pass.  This is needed for integration tests.

new fiberassign file names for newexp

---

.travis.yml
doc/conf.py
py/desisim/pixsim.py
py/desisim/scripts/newarc.py
py/desisim/scripts/newflat.py
py/desisim/simexp.py
py/desisim/util.py

This PR adds `freeze_iers()` calls where needed to prevent downloads of the IERS-A table.  At this point, I have updated pixsim.py, such that it can run to completion during integration tests, but the logging output from the integration test indicates that there are other modules or executables that are attempting the download, possibly `newexp-random`.
Do not merge until the additional download attempts are isolated.

[WIP] Add freeze_iers

---

.travis.yml
py/desisim/pixsim.py
py/desisim/scripts/newarc.py
py/desisim/scripts/newflat.py
py/desisim/simexp.py
py/desisim/util.py

This PR replaces desisurvey.utils.freeze_iers with desiutil.iers.freeze_iers to remove the desisurvey dependency in desisim and get a version of freeze_iers that works with astropy 3.x and 4.x.
Requires desiutil >= 2.0.3 .
Intended for software release 20.4, with tags to be made this afternoon (i.e. comment quickly if you have concerns).

use desiutil.iers.freeze_iers instead of desisurvey.utils.freeze_iers

---

py/desisim/scripts/quickquasars.py
py/desisim/scripts/quickspectra.py

Their PR is to allow quickquasars to produce mocks with pixels width specified by the user. This is related to the more general issue  raised by Andreu https://github.com/desihub/desisim/issues/532. 
Change is very simple, I've tested it in a small run here /global/cfs/projectdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0/v9.0.0/desi-1.2-1.tmp/ 
I was waiting for some feedback from the DLA team, but I think it will be fine if we just go ahead. 
**Other changes are only some missing spaces I added ...

Add dwave out to quickquasars

---

doc/changes.rst
py/desisim/quickcat.py

This simple fix will allow reading either `fba-` or `fiberassign-` files to build a redshift catalog. The old hardcoded option only works for `fiberassign-` files.

new keyword in quickcat to indicate which HDU to read in fba files

---

bin/wrap-fastframe
py/desisim/io.py
py/desisim/simexp.py
py/desisim/test/test_obs.py

More updates for supporting fitsio 1.x (str) vs. <1 (bytes), this time in `desisim.simexp.read_mock_spectra`.  It includes a new unit test that piggy backs upon the test mock spectra in desitarget.
This also updates `desisim.io.write_simspec` to use a temporary file when writing to avoid partially written files with the final filename.
Reviews from anyone are welcome, but this is needed for next software release so I'll leave it open for a bit while testing other repos, but I will self merge this when needed for a desisim tag.

fitsio str vs. bytes

---

py/desisim/obs.py

Fixes #547 where pixsim tests were failing due to negative pixels being passed to `np.poisson()`.  It turns out that `desi/spectro/templates/calib/v0.4/arc-lines-average-in-vacuum-from-winlight-20170118.fits` has some negative values in the wings of arc lines.  Prior to [specter commit #6a0d107](https://github.com/desihub/specter/commit/6a0d10766f4b187d3c5151c40797b6d9c8d745c5), `psf.project` was clipping these negative values but now it allows you to project negative values if you really really want to so you have to fix it on the input side.
The fix is simple: clip negative values from the input arc file prior to simulating.

fix negative arc line ringing

---

py/desisim/pixsim.py

This PR fixes the formatting of the CCDSIZE header keyword in simulated data.
Correct, matches real data format:
```
CCDSIZE = '4096,4204'
```
Previous, incorrect:
```
CCDSIZE = '(4096, 4204)'
```
Until yesterday this keyword wasn't used and thus wasn't a problem, but now it is used by the TSNR calculation in desispec which was failing on simulated data due to this keyword.  Nightly integration tests at NERSC caught the problem.

fix CCDSIZE keyword formatting in simulated raw data

---

py/desisim/scripts/fastframe.py

This PR adds some header keywords that were missing from simulated output.  New template S/N ratio (TSNR) code in the spectro pipeline now requires these keywords, which was breaking the integration testing.  Hardcoding the CCDSIZE is admittedly yucky, but I didn't see how to access that information from the params available to fastframe at that point in the code.  I'm going to proceed with this so that I can proceed with integration testing, but if someone cares deeply enough they can separately contribute a cleaner solution later.

add missing header keywords

---

.github/workflows/python-package.yml
doc/changes.rst
py/desisim/data/forbidden_lines.ecsv
py/desisim/data/recombination_lines.ecsv
py/desisim/scripts/quickquasars.py
py/desisim/targets.py
py/desisim/templates.py
py/desisim/test/test_templates.py
requirements.txt

`desisim.templates` has been broken for some time (e.g., https://github.com/desihub/desisim/issues/553). The changes in this PR are needed to restore everything to a working state. 
WIP so not quite ready to merge. 
The companion PRs are https://github.com/imcgreer/simqso/pull/33 and https://github.com/desihub/desitarget/pull/786. However, I'm having trouble getting the Github actions tests to pass even though they pass on my laptop. I'll keep trying.
One of the "major" changes is that `desisim.templates` now has to estimate the fiberflux for the ELG and LRG target classes, in order to retrieve templates / models which pass our nominal color-cuts. Since the template-generating code doesn't know much physics, I opted to generate these fluxes statistically, using data from SV3. 
Here's my …

restore template-generating code to a working state

---

.github/workflows/python-package.yml
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/templates.py
py/desisim/test/test_quickgen.py
py/desisim/test/test_quickquasars.py
py/desisim/test/test_templates.py
py/desisim/test/test_top_level.py
requirements.txt
setup.py

[WIP]
In this mishmash PR I'm planning to address #507, #537, #549, and #558. I'll provide details of the changes when I'm done.

updates and fixes to template-generating code and failing unit tests and errors

---

py/desisim/scripts/gen_qso_catalog.py
py/desisim/scripts/quickquasars.py
py/desisim/survey_release.py

This Pull request addresses various of the requested changes that were pending in #578. Most of the comments were addressed except for one:
> Ah this is the seed. I recommend creating a member random engine `rng_engine = np.random.default_rng(seed)` and calling it to generate the random numbers you need. `default_rng` is recommended since numpy 1.17
I tested doing this and the resulting catalogs are different than the obtained with the currently implemented method. For the sake of reproducibility of the KP6 mocks I will leave it as is. Changing to a random engine will be left for future implementations.
Some additional changes in this PR:
1. Fixed a bug causing `quickquasars` to assign the magnitudes and exposure times from the input catalog to the incorrect MOCKID. This happens if the …

Pending changes requested on previous PR, from_catalog fix for Ohio mocks

---

py/desisim/scripts/gen_qso_catalog.py
py/desisim/survey_release.py

This Pull Request includes updates in py/desisim/survey_release.py and the py/desisim/scripts/gen_qso_catalog.py script in order to be able to produce DESI-Y3 mocks. 
Mayor updates:
- `survey_release.py` does not require HEALpix Pixel map of the number of tiles covering a region (NPASS) to function anymore. Instead it is internally generated based on a `tiles-<release>.fits` file within the DESI_SPECTRO_REDUX directory by default. This tile file might be an input if a custom footprint is desired.
- `survey_release.py` now includes the option to select mock objects in order to mimicking the characteristics of  non-qso targets included in the observed data catalog.
Minor updates:
- `gen_qso_catalog.py`: changed `--input-data` flag to None by default instead of the iron release observed Lya …

Update to generate DESI-Y3 Lya mocks

---

.github/workflows/python-package.yml
doc/conf.py
requirements.txt
setup.py

This PR removes `desiutil.setup.DesiTest` from setup.py.
It looks like the format of `desimodel/data/focalplane/platescale.txt` has changed since the last time desisim was successfully tested, and that is causing the majority of the test errors.

Remove DesiTest
