desihub/desisim

doc/index.rst
etc/desisim.module
py/desisim/__init__.py
setup.py

This pull request should add the minimal set of files to make desisim compatible with desiInstall.

Desi install

---

bin/quickGen.py

Based on Stephen's comments, changes have been implemented. Comments/ Suggestions are welcome.
Thanks

Added Directory tree, modified coding style, indentation, dictionary etc

---

py/qso_template/__init__.py
py/qso_template/boss_qsos_figs.py
py/qso_template/desi_qso_templ.py
py/qso_template/fit_boss_qsos.py
py/qso_template/qso_pca.py
py/qso_template/run_qso_fits.py
py/qso_template/tests.py

Code for preliminary qso_templates, v1.1

Qso template

---

bin/quickGen.py

Sparse matrix is created inside, with intention of making very little change the existing quicksim.

resampling and resolution defined inside

---

bin/quicksurvey
py/desisim/__init__.py
py/desisim/targets.py

Updated targets.py with the classes used for bookkeeping during fiber assignment.
Added script quicksurvey to test new classes and functions. Also to learn how to reuse code already written in desisim/desimodel/desispec.

Format flow

---

py/desisim/spec_qa/high_level.py

Small edit to handle desispec update.

updated to rawdata_root

---

bin/quickgen

This PR focusses the suggested changes and addresses the issues of not going beyond 500 spectra or spectrograph 1-9. Also did some recorganization for writing the files etc. Can well test a ~5000 spectra simspec file. I only had ~ O(2000), where all the suggested tests worked fine.

Fix the spectrograph higher than 0 and nspec beyond 500

---

bin/quickbrick
py/desisim/filterfunc.py
py/desisim/templates.py

ready for the first redshift data challenge

Quickbrick2

---

py/desisim/pixsim.py

This PR fixes #74 by calculating the cosmic ray mask after adding the signal rather than using the overly clean cosmic ray mask that was calculated before signal was added.  The image below shows a pixsim with cosmics (left) and with the mask applied (right).

add cosmic ray masking to pixsim

---

.travis.yml
py/desisim/templates.py

uses isMWSSTAR_colors to get a more reasonable g-r range for an old stellar population

desisim fix to MWS_STAR colors

---

bin/quicksurvey
bin/quicksurvey_stats
py/desisim/quickcat.py
py/desisim/quicksurvey.py

First implementation of quicksurvey class and scripts. Runs a DESI simulation starting from a truth file, target file and epoch files. 
It creates a Merged Target List, runs fiber assignment and creates a redshift catalog for each epoch.
The class also includes a function to get rough efficiency statistics.

Quicksurvey

---

py/desisim/pixsim.py

This PR fixes issue #121 (checked with a simulation run at NERSC)

Fix cosmicsims

---

py/desisim/spec_qa/redshifts.py

Several changes to ztruth to enable integration tests
in desispec.
Mainly allows for small number of sources,
including 0 in various object types.
Failing coverage test but unlikely due to these changes.

Integration with ztruth

---

bin/desi_qa_zfind
py/desisim/spec_qa/redshifts.py

Edits to QA for integration tests 
cron job was failing.. 
This may fix it

QA edits for cron job

---

py/desisim/obs.py

This PR is needed for realistic arc lamp images.

use desisim throughput for varying arc lines in cameras

---

.travis.yml
doc/api.rst
doc/changes.rst
doc/conf.py
doc/index.rst
py/desisim/__init__.py
py/desisim/io.py
py/desisim/obs.py
py/desisim/pixsim.py
py/desisim/quickcat.py
py/desisim/targets.py
py/desisim/templates.py

This PR
* Fixes #163 
* Updates sphinx configuration.
* Updates a lot of doc strings so documentation can be built without errors. 
* We have never actually put desisim on ReadTheDocs, but because of these fixes, we should be able to do so without any problems.

Sphinx and coverage fixes

---

doc/changes.rst
etc/desisim.module

Updates Module file to DESI+Anaconda infrastructure.

update module file

---

py/desisim/scripts/quickgen.py

This PR
- Changes $PRODNAME to $SPECPROD.
- Changes os.path.join to desispec.io.findfile.
- Changes print statements to log.info().

Quickgen update

---

doc/changes.rst
py/desisim/scripts/quickbrick.py
py/desisim/scripts/quickgen.py
py/desisim/test/test_quickgen.py

This PR
- Adds moon phase, moon angle, and zenith angle to quickgen via optional keyword arguments.
- Adds unit tests for each additional moon property.
- Updates changes.rst to include recent quickgen developments.

Quickgen moon

---

py/desisim/scripts/quickbrick.py
py/desisim/scripts/quickgen.py
py/desisim/test/test_quickbrick.py
py/desisim/test/test_quickgen.py

This PR
- Updates quickgen, quickbrick, and the respective unit tests with proper keyword arguments for moon parameters.

update moon keywords

---

py/desisim/quickcat.py
py/desisim/quicksurvey.py
py/desisim/test/test_quickcat.py

Here are some updatates to `quickcat`, as a first approximation to solve #182.
* `get_observed_redshifts_obsconditions` is a new function that uses a dictionary with `obsconditions` to estimate redshift success. It is based on Kyle's code. `quickcat.quickcat` now uses that function.
* `get_obsconditions` generates the `obsconditions` dictionary waiting for `surveysim` coupling.
* `get_observed_redshifts_zmag` is a place holder for a function that estimates redshift success based on true redshift and observed magnitudes. It is not used yet.

New quickcat interface

---

py/desisim/quickcat.py

This PR corrects a bug in the way output redshifts were computed for all targets.

Debug quickcat

---

py/desisim/scripts/quickgen.py

This PR:
- Adds white dwarfs to the quickgen brick mode.

added wd templates

---

py/desisim/templates.py
py/desisim/test/test_templates.py

This PR adds an option for generating restframe templates for subclasses of SUPERSTAR and GALAXY (but not yet QSO).

add option for restframe templates

---

doc/changes.rst
py/desisim/templates.py

This adds the option of choosing more verbose output (DEBUG-level) when generating templates. (Un)surprisingly very useful for debugging!

add a verbose optional input to desisim.templates

---

doc/changes.rst

We (I) forgot to update `changes.rst` before merging #234.

updated changes.rst for #234

---

py/desisim/lya_spectra.py

A `nocolorcuts=True` option is needed for https://github.com/desihub/desitarget/pull/186. 
This also includes a (minor) bug fix: although we were (re)normalizing the spectrum by the g-band magnitude from the Lya mocks we weren't scaling the DECam and WISE fluxes.

add nocolorcuts option; scale photometry

---

.travis.yml
py/desisim/templates.py

This fixes https://github.com/desihub/desisim/issues/245, which broke after https://github.com/desihub/desitarget/pull/179 and https://github.com/desihub/desitarget/pull/194.

use isLRG_colors for color-cuts

---

py/desisim/obs.py
py/desisim/scripts/brightsims_aug2017.py
py/desisim/targets.py
py/desisim/templates.py

Created new functions to specify target parameters in templates.py. Code now propagates a dictionary to get_targets and unpacks into make_templates. All defaults maintained. Old function calls should not see any changes.

BGS Simulation parameter propagation

---

.travis.yml
doc/changes.rst
py/desisim/scripts/qa_s2n.py
py/desisim/scripts/qa_zfind.py
py/desisim/simexp.py
py/desisim/spec_qa/redshifts.py
py/desisim/spec_qa/s2n.py
py/desisim/spec_qa/utils.py

Changes from input at desi data telecon (15 Aug 2017):
* Added BGS, MWS to redshift QA
* Calculate S/N per Ang instead of per pix
* Change to velocity units for 2D redshift histograms
* Extend [OII] flux range for ELGs below requirement threshold
* Clip before calculating RMS of redshift deviates
Here is the BGS output:

QA Polishing

---

py/desisim/quicksurvey.py

This PR is updated to process the new `surveysim` output files.
The key aspect is checking that copying and pasting the commands in `readme.ipynb` work as written there.

quicksurvey runs on recet surveysim outputs

---

bin/pixsim_mpi
bin/wrap-newexp
py/desisim/scripts/newexp_mock.py

This PR closes #273 by deriving all input for `wrap-newexp` from the input obslist/exposures file.

Exposures as obslist

---

py/desisim/scripts/qa_zfind.py

Addresses an issue noted by @julienguy

Add objtypes in qa_zfind

---

py/desisim/quicksurvey.py

Minor update in `quicksurvey` to handle new data formats in `exposures` files.

handles new date formats

---

doc/index.rst
doc/qa.rst
py/desisim/scripts/qa_s2n.py
py/desisim/spec_qa/__init__.py

Add r camera for desi_qa_s2n
Added docs

QA: docs and qa_s2n improvement

---

doc/changes.rst
doc/qa.rst
py/desisim/scripts/qa_s2n.py
py/desisim/scripts/qa_zfind.py
py/desisim/spec_qa/__init__.py
py/desisim/spec_qa/redshifts.py

Updated scripts (slightly) and docs.
Mainly to prepare for modifying the mini test Notebook.
Failing Travis but not possibly because of this PR.

QA edits for running mini test

---

py/desisim/scripts/fastframe.py

change of units for simulated frames

photons/bin -> photons/Angstrom and optional dwave with default = 0.8A

---

py/desisim/simexp.py

Add argument to use a custom DESI instrument configuration (default is 'desi' from specsim package)
(needed to study changes in instrumentation)

Specsim config

---

py/desisim/simexp.py

This PR implements more robust handling of unassigned fibers from fiberassign, which currently have RA,DEC = NaN,NaN and TARGETID<0.  This PR catches these cases and simulates them as sky fibers (but not setting DESI_TARGET as sky so that they won't be used for the sky model).
I don't understand why this hasn't bitten us in previous integration tests which also had unassigned fibers.
Longer term we need upstream updates for unassigned fibers (e.g. they are pointing somewhere, not at (RA, dec) = (NaN, NaN)), but this provides a stop-gap solution for the 18.3 software release.

more robust handling of unassigned fiber input

---

doc/changes.rst

This PR fixes a few minor formatting errors in the doc/changes.rst file.

Fix minor problems in doc/changes.rst

---

doc/changes.rst
py/desisim/io.py
py/desisim/pixsim.py
py/desisim/scripts/pixsim.py

This pull request fixes a previous bug in which the cameras were not properly divided between nodes in pixsim. This pull request also significantly cuts down on memory overhead in read_simspec_mpi, allowing the processes to stay under the cori haswell node memory limit.

One month pixsim

---

py/desisim/scripts/quickquasars.py
py/desisim/scripts/quickspectra.py

Solving issue https://github.com/desihub/desispec/issues/567
Writes HPXNSIDE HPXPIXEL HPXNEST keywords in spectra files generated with quickquasars .

Healpix in spectra header

---

py/desisim/scripts/quickquasars.py
py/desisim/scripts/quickspectra.py

Optionally compute magnitudes in quickquasars and save them in hdu SCORES of the spectra files.

Quickquasars mags

---

py/desisim/io.py

In a munged git operation, I accidentally added a bunch of work-in-progress simspec I/O changes to PR #351, which broke the tests.  This PR at least fixes the tests (on my laptop; we'll see if Travis agrees).
With apologies to @lastephey, this probably created problems for the big_pixsim branch, which I will also try to rectify in a subsequent update.

fix broken WIP simspec I/O

---

py/desisim/pixsim.py
py/desisim/scripts/pixsim_nights.py

This PR adds a `pixsim_nights --nexp` option to limit the number of exposures that it will try to do.  This is useful for testing and for production runs to achieve an efficient packing of exposures and nodes.
It also adds logic to skip exposures that have already been processed, which is useful if your job times out and you want to pickup where you left off.  Assisting that is reviving the `--overwrite` option if you really do want to overwrite them, and also writing to a temporary output file before moving that into place so that we don't leave partial files behind.
This PR also comments out some other options that had gotten lost along the way in the recent refactor: `--seed`, `--nspec`, `--wavemin`, `--wavemax`.  We'd like to get those back, but for now it is better for them to not be …

update pixsim_nights options

---

py/desisim/scripts/quickquasars.py

Change to quickquasars to read healpix nside and scheme from header.

read healpix nside and scheme from header

---

py/desisim/scripts/quickquasars.py

Reverts desihub/desisim#371
To see why travis is failing

Revert "Qqso dla bal"

---

py/desisim/lya_spectra.py
py/desisim/scripts/quickquasars.py

@julienguy New try to merge with master. Includes dla and bal features

Qqsuasar dlas

---

py/desisim/scripts/newexp_mock.py

Addresses https://github.com/desihub/desisim/issues/378

update extension name of fiber-assignment output file

---

doc/changes.rst
py/desisim/templates.py

PR to address https://github.com/desihub/redrock-archetypes/pull/4.

optionally change the min/max wavelength and resolution in SIMQSO's basewave wavelength vector

---

py/desisim/dla.py
py/desisim/scripts/quickquasars.py

Fixes a couple of issues when adding DLAs. Tested running in full London mock.

Fix dlabugs

---

.travis.yml
doc/changes.rst
py/desisim/io.py
py/desisim/qso_template/desi_qso_templ.py
py/desisim/qso_template/fit_boss_qsos.py
py/desisim/spec_qa/high_level.py
requirements.txt

This PR converts `astropy.io.fits` argument `clobber` to `overwrite` to avoid deprecation warnings.

clobber -> overwrite

---

etc/quickquasar_slurm_script.sh
py/desisim/scripts/quickquasars.py

Ask for one seed per file, for example:
```
quickquasars --exptime 4000.
-i /project/projectdirs/desi/mocks/lya_forest/london/v2.0//9/931/transmission-16-931.fits
/project/projectdirs/desi/mocks/lya_forest/london/v2.0//9/932/transmission-16-932.fits
--zmin 1.8 --nproc 4
--outdir /project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.4//spectra-16
--downsampling 0.40 --zbest --mags --desi-footprint
--seed 937728865 159455235
--metals all --nmax 1
```

different seeds for each jobs

---

py/desisim/scripts/quickquasars.py

This will allow tests of Redrock without Lyman alpha forest absorption. 
I've tested that it works, it should be a very straightforward PR.

add option to ignore transmission in quickquasars, effectively using F=1 everywhere

---

doc/changes.rst
py/desisim/scripts/fastframe.py

Electrons to counts

---

py/desisim/archetypes.py

fix print step archetype computation: fix https://github.com/desihub/desisim/issues/425

fix print step archetype computation

---

py/desisim/quickcat.py

update target efficiency using redwood: fix issue https://github.com/desihub/desisim/issues/355

update target efficiency redwood

---

doc/changes.rst
py/desisim/templates.py

Addresses the updated BGS target cuts implemented in https://github.com/desihub/desitarget/pull/407.

support new BGS target cuts

---

py/desisim/scripts/quickquasars.py

fix error in size of Z_noFOG, the selection in the eBOSS case was not applied.

fix error in size of Z_noFOG

---

py/desisim/scripts/quickquasars.py

Added a shift to the redshift according to issue https://github.com/desihub/desisim/issues/442  I thought this was done, but it seems I lost the changes just before merging to master. Here it goes again. @londumas I'll merge when you agree.

add shift to redshift

---

py/desisim/scripts/quickspectra.py

Remove remaining matplotlib

---

py/desisim/scripts/quickquasars.py

Update eBOSS magnitude to be closer to data.
This is not exact science, but let's start with that and we will have a better picture after 10 realizations.

Update eBOSS magnitude to be closer to data

---

py/desisim/qso_template/fit_boss_qsos.py
py/desisim/qso_template/qso_pca.py

Fix issue https://github.com/desihub/desisim/issues/476 by updating all found lya lines to `1215.67`.

Update the value of the Lya absorption line

---

py/desisim/scripts/quickquasars.py

Fix issue https://github.com/desihub/desisim/issues/482 by using `TARGETID` everywhere, before only DLA hdu was using `MOCKID`.

Use TARGETID for DLA hdu

---

py/desisim/lya_spectra.py

Add higher order Lyman absorption.

Add shorter than Lyb absorption

---

py/desisim/lya_spectra.py
py/desisim/scripts/lya_simqso_model.py
py/desisim/scripts/quickquasars.py

Fix issue using the boost. boost is float, not list

Fix issue using the boost

---

py/desisim/quicksurvey.py

This PR updates quicksurvey.py to use the updated tile file naming convention.
@sbailey Please review these changes.

update quicksurvey to use new tile file naming convention

---

.travis.yml
py/desisim/scripts/fastframe.py
py/desisim/simexp.py
py/desisim/targets.py
requirements.txt

This PR is a companion to desihub/desispec#821 to handle the renaming of DESIGN_X/Y -> FIBERASSIGN_X/Y.  I'm still testing at NERSC with the minitest notebook, but I'm opening this PR now to get Travis testing going too.

Fiberassign xy

---

py/desisim/lya_spectra.py
py/desisim/scripts/quickquasars.py

I made the small fixes in lya_spectra and quickquasars. 
- Apply the indices mask after adding Metals and LYB to transmission. Needed in order to be used from mockmaker.
- Added a few more info to display when running
- Fixed a couple of (non-very important) identified bugs

Minor fixes	

---

doc/changes.rst
py/desisim/simexp.py
py/desisim/templates.py
py/desisim/test/test_obs.py

[WIP] PR to address #534 and #535.

address sky-level unit test failure and template normalization bug

---

py/desisim/scripts/quickquasars.py

Addressing issue #543 . The change is quite simple, just added the optional argument and saved in a different hdu in the truth file. Works well with the different options I tested, and you can find a full run here /global/project/projectdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0/v9.0.0/axgm-0.0-1000-continum

Add option to save true continum

---

.github/workflows/python-package.yml
requirements.txt

in requirements.txt and github/workflows/python-package.yml

Update master to main 

---

doc/changes.rst
py/desisim/io.py

added sort to find_basis_template()
